teste de hadolint

diff --git a/.github/workflows/03-build-containers.yml b/.github/workflows/03-build-containers.yml
--- a/.github/workflows/03-build-containers.yml
+++ b/.github/workflows/03-build-containers.yml
@@ -40,6 +40,14 @@ jobs:
           push: false
           tags: ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
 
+      - name: Lint Dockerfile with Hadolint
+        run: |
+          hadolint Dockerfile > lint-report.txt
+          if grep -qE "DL3006|DL3008" lint-report.txt; then
+            echo "Linting failed due to DL3006 or DL3008." && exit 1;
+          fi
+        shell: bash
+
   generate-certificate: # DAQUI PARA BAIXO, NÃO ALTERAR
     name: "Desafio Nível 3 - Certificado"
     needs: build-scan-and-push
