acertando lugar do hadolint

diff --git a/.github/workflows/03-build-containers.yml b/.github/workflows/03-build-containers.yml
--- a/.github/workflows/03-build-containers.yml
+++ b/.github/workflows/03-build-containers.yml
@@ -24,6 +24,14 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      - name: Lint Dockerfile with Hadolint
+        run: |
+          hadolint Dockerfile > lint-report.txt
+          if grep -qE "DL3006|DL3008" lint-report.txt; then
+            echo "Linting failed due to DL3006 or DL3008." && exit 1;
+          fi
+        shell: bash
+
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -39,14 +47,6 @@ jobs:
           file: ./Dockerfile
           push: false
           tags: ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
-
-      - name: Lint Dockerfile with Hadolint
-        run: |
-          hadolint Dockerfile > lint-report.txt
-          if grep -qE "DL3006|DL3008" lint-report.txt; then
-            echo "Linting failed due to DL3006 or DL3008." && exit 1;
-          fi
-        shell: bash
 
   generate-certificate: # DAQUI PARA BAIXO, NÃO ALTERAR
     name: "Desafio Nível 3 - Certificado"
